/*
 * @file    Font18.c
 * @brief   LVGL XBF font Font18 stored in the SPI-NOR font store
 *          (generated by tool/lvgl_font_c2xbf.py - do not edit).
 */

#include "lvgl.h"
#include "nor.h"
#include "text.h"

typedef struct {
    uint16_t min;
    uint16_t max;
    uint8_t  bpp;
    uint8_t  reserved[3];
} x_header_t;
typedef struct {
    uint8_t adv_w;
    uint8_t box_w;
    uint8_t box_h;
    int8_t  ofs_y;
} glyph_dsc_t;

static x_header_t __g_xbf_hd = {0, 0, 0};
static uint8_t __g_font_buf[273];

static uint8_t *__user_font_getdata(int offset, int size)
{
    nor_read(__g_font_buf, ftinfo.lvgl_18addr + (uint32_t)offset, (uint16_t)size);
    return __g_font_buf;
}

static const uint8_t *__user_font_get_bitmap(const lv_font_t *font, uint32_t unicode_letter)
{
    (void)font;
    if (__g_xbf_hd.max == 0)
    {
        memcpy(&__g_xbf_hd, __user_font_getdata(0, sizeof(x_header_t)), sizeof(x_header_t));
    }
    if (unicode_letter > __g_xbf_hd.max || unicode_letter < __g_xbf_hd.min)
    {
        return NULL;
    }
    uint32_t unicode_offset = sizeof(x_header_t) + (unicode_letter - __g_xbf_hd.min) * 4;
    uint32_t pos = *(uint32_t *)__user_font_getdata(unicode_offset, 4);
    if (pos != 0)
    {
        glyph_dsc_t *gdsc = (glyph_dsc_t *)__user_font_getdata(pos, sizeof(glyph_dsc_t));
        return __user_font_getdata(pos + sizeof(glyph_dsc_t), gdsc->box_w * gdsc->box_h * __g_xbf_hd.bpp / 8);
    }
    return NULL;
}

static bool __user_font_get_glyph_dsc(const lv_font_t *font, lv_font_glyph_dsc_t *dsc_out,
                                      uint32_t unicode_letter, uint32_t unicode_letter_next)
{
    (void)font;
    (void)unicode_letter_next;
    if (__g_xbf_hd.max == 0)
    {
        memcpy(&__g_xbf_hd, __user_font_getdata(0, sizeof(x_header_t)), sizeof(x_header_t));
    }
    if (unicode_letter > __g_xbf_hd.max || unicode_letter < __g_xbf_hd.min)
    {
        return false;
    }
    uint32_t unicode_offset = sizeof(x_header_t) + (unicode_letter - __g_xbf_hd.min) * 4;
    uint32_t pos = *(uint32_t *)__user_font_getdata(unicode_offset, 4);
    if (pos != 0)
    {
        glyph_dsc_t *gdsc = (glyph_dsc_t *)__user_font_getdata(pos, sizeof(glyph_dsc_t));
        dsc_out->adv_w = gdsc->adv_w;
        dsc_out->box_h = gdsc->box_h;
        dsc_out->box_w = gdsc->box_w;
        dsc_out->ofs_x = 0;
        dsc_out->ofs_y = gdsc->ofs_y;
        dsc_out->bpp   = __g_xbf_hd.bpp;
        return true;
    }
    return false;
}

lv_font_t Font18 = {
    .get_glyph_bitmap = __user_font_get_bitmap,
    .get_glyph_dsc = __user_font_get_glyph_dsc,
    .line_height = 19,
    .base_line = 0,
};
