set(MCU STM32F429IGTx CACHE STRING "MCU")

if(MCU STREQUAL "STM32F429IGTx")
    set(MCU_ARCH       cortex-m4)
    set(MCU_VENDOR     stm32)
    set(MCU_FAMILY     stm32f4xx)
    set(MCU_MACRO      STM32F429xx)
    set(MCU_HSE_VALUE  25000000)
    set(MCU_HSI_VALUE  16000000)
    set(MCU_TARGET_DIR ${MCU_VENDOR}/${MCU_FAMILY})

    set(MCU_BOOT_MODE flash CACHE STRING "Boot mode (flash|ram)")
    if(MCU_BOOT_MODE STREQUAL "flash")
        set(MCU_FLASH_BASE 0x08000000)
        set(MCU_LD_SUFFIX  flash)
    elseif(MCU_BOOT_MODE STREQUAL "ram")
        set(MCU_FLASH_BASE 0x20000000)
        set(MCU_LD_SUFFIX  ram)
    else()
        message(FATAL_ERROR "Invalid MCU_BOOT_MODE: ${MCU_BOOT_MODE}")
    endif()
else()
    message(FATAL_ERROR "Unsupported MCU: ${MCU}")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/../cpu/${MCU_ARCH}.cmake)

set(BSP openedv_stm32f4 CACHE STRING "Board Support Package")

if(BSP STREQUAL "openedv_stm32f4")
    set(BSP_DRV stm32_hal)
else()
    message(FATAL_ERROR "Unsupported BSP: ${BSP}")
endif()

set(OPENOCD openocd CACHE FILEPATH "openocd executable")
set(OPENOCD_INTERFACE cmsis-dap.cfg CACHE STRING "OpenOCD interface cfg")
set(OPENOCD_TARGET    stm32f4x.cfg  CACHE STRING "OpenOCD target cfg")
