# openedv ATK-F429 (Apollo) / STM32F429IGTx

set(CPU "cortex-m4" CACHE INTERNAL "")
set(DEVICE_FAMILY "stm32f4" CACHE INTERNAL "")
set(DEVICE_DEFINE "STM32F429xx" CACHE INTERNAL "")
set(BOARD_HSE_HZ 25000000 CACHE INTERNAL "")

set(TARGET_DIR "${CMAKE_SOURCE_DIR}/target/${DEVICE_FAMILY}" CACHE INTERNAL "")
set(TARGET_LD_SCRIPT "${TARGET_DIR}/stm32f429igtx_flash.ld" CACHE INTERNAL "")
